services:
  - type: web
    name: dataswift-backend
    env: python
    region: singapore
    buildCommand: |
      export POETRY_PYTHON=false
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.18   # ✅ Downgraded from 3.13
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /health
    buildFilter:
      paths:
        - backend/**
